config/routes.rb
Trasform::Application.routes.draw do
  resources :categories

  get "home/index"
  
  resources :forms
  
  resources :category
  

  
  root :to => 'home#index', as: 'home'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :path
  validates :name, :path, presence: true
  validates :path, uniqueness: true,
  format: { 
    with: %r{\A(\d{0,2}\.){1}(\d{0,2}\.){0,1}(\d{0,2}\.){0,1}(\d{0,2}\.){0,1}\Z}i,
    message: 'must be look likes "1." or "3.1." or "10.2.30.4.".'
  }

  def full_title
    "#{path} #{name}"
  end

  def parent_path
    parent = path.gsub(/
end

app/models/form.rb
class Form < ActiveRecord::Base
 
  attr_accessible :type_of_legal_entity, :actual_address, :address_on_english, :auditors_name, :bank_name, :bank_person, :bik, :categories_list_of_works, :company, :correspondent_account, :creator_name, :current_account, :email, :fax, :inn, :kpp, :ogrn, :phone, :registered_address, :type_of_certificate
  
  before_validation :normalize_phone, :normalize_fax, :attributes
  
  def normalize_phone
    self.phone.gsub(/[^\d]/, "")
  end
  
  def normalize_fax
    self.fax.gsub(/[^\d]/, "")
  end
  
  validates :type_of_legal_entity, :bank_name, :bank_person, :categories_list_of_works, :company, :creator_name, :type_of_certificate, presence: true
  validates :bik, presence: true, format: { with: %r{\d{9}}i, message: 'must be contain nine numbers.' }
  validates :correspondent_account, presence: true, format: { with: %r{\d{20}}i, message: 'must be contain twenty numbers.' }
  validates :current_account, presence: true, format: { with: %r{\d{20}}i, message: 'must be contain twenty numbers.' }
  validates :email, presence: true, format: { with: %r{\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z}i }
  validates :fax, presence: true, format: { with: %r{\d{7,11}}i }
  validates :inn, presence: true, format: { with: %r{\d{10}}i, message: 'must be contain ten numbers.' }
  validates :kpp, presence: true, format: { with: %r{\d{9}}i, message: 'must be contain nine numbers.' }
  validates :ogrn, presence: true, format: { with: %r{\d{13}}i, message: 'must be contain thirteen numbers.' }
  validates :phone, presence: true, format: { with: %r{\d{7,11}}i }
  validates :auditors_name, presence: true
  validates :actual_address, :address_on_english, :registered_address, presence: true, format: { with: %r{\A\d{6}\,}i, message: 'must start with the postal code("123456, City, street").' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  # GET /forms
  # GET /forms.json
  def index
    @forms = Form.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @forms }
    end
  end

  # GET /forms/1
  # GET /forms/1.json
  def show
    @form = Form.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @form }
    end
  end

  # GET /forms/new
  # GET /forms/new.json
  def new
    @form = Form.new
    
    @categories_with_parent_path = {}
    category_matchers = [/\A(\d+\.){1}\z/, /\A(\d+\.){2}\z/, /\A(\d+\.){3}\z/, /\A(\d+\.){4}\z/]

    category_matchers.each do |matcher|
      matched_categories = Category.all.sory_by(&:path).select { |category| category.path =~ matcher }
      @categories_with_parent_path[matched_categories.first.path] = matched_categories
    end

    #@level_1_categories = Category.all.select { |category| category.path =~ /\A\d+\.\z/ }

    #level_2_categories = Category.all.select { |category| category.path =~ /\A\d+\.\d+\.\z/ }
    #@level_2_categories_with_parent_ids = {}
    #@level_1_categories.each do |cat|
    #  @level_2_categories_with_parent_ids[cat.path] = level_2_categories.select { |c| c.path =~ /\A#{cat.id}+\./ }
    #end

    #level_3_categories = Category.all.select { |category| category.path =~ /\A\d+\.\d+\.\d+\.\z/ }
    #@level_3_categories_with_parent_ids = {}
    #level_2_categories.each do |cat|
    #  @level_3_categories_with_parent_ids[cat.path] = level_3_categories.select { |c| c.path =~ /\A\d+\.#{cat.id}+\./ }
    #end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @form }
    end
  end

  # GET /forms/1/edit
  def edit
    @form = Form.find(params[:id])
  end

  # POST /forms
  # POST /forms.json
  def create
    @form = Form.new(params[:form])

    respond_to do |format|
      if @form.save
        format.html { redirect_to @form, notice: 'Form was successfully created.' + @form }
        format.json { render json: @form, status: :created, location: @form }
      else
        format.html { render action: "new" }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /forms/1
  # PUT /forms/1.json
  def update
    @form = Form.find(params[:id])

    respond_to do |format|
      if @form.update_attributes(params[:form])
        format.html { redirect_to @form, notice: 'Form was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json
  def destroy
    @form = Form.find(params[:id])
    @form.destroy

    respond_to do |format|
      format.html { redirect_to forms_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :path %><br />
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Категории</h1>

<table>
  <tr>
    <th>Path</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.path %></td>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Path:</b>
  <%= @category.path %>
</p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %> |
<%= link_to 'New Category', new_category_path %>

app/views/forms/_form.html.erb
<%= form_for(@form) do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form.errors.count, "ошибок") %> найдено в следующих полях:</h2>

      <ul>
      <% @form.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type_of_legal_entity, t(:type_of_legal_entity) %>
    <%= f.select :type_of_legal_entity, options_for_select(["ООО", "ИП", "ЗАО", "ОАО"]) %>
  </div>
  <div class="field">
    <%= f.label :company, t(:company) %>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :creator_name, t(:creator_name) %>
    <%= f.text_field :creator_name %>
  </div>
  <div class="field">
    <%= f.label :registered_address, t(:registered_address) %>
    <%= f.text_field :registered_address %>
  </div>
  <div class="field">
    <%= f.label :actual_address, t(:actual_address) %>
    <%= f.text_field :actual_address %>
  </div>
  <div class="field">
    <%= f.label :address_on_english, t(:address_on_english) %>
    <%= f.text_field :address_on_english %>
  </div>
  <div class="field">
    <%= f.label :phone, t(:phone) %>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :fax, t(:fax) %>
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :email, t(:email) %>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :inn, t(:inn) %>
    <%= f.text_field :inn %>
  </div>
  <div class="field">
    <%= f.label :kpp, t(:kpp) %>
    <%= f.text_field :kpp %>
  </div>
  <div class="field">
    <%= f.label :ogrn, t(:ogrn) %>
    <%= f.text_field :ogrn %>
  </div>
  <div class="field">
    <%= f.label :bank_name, t(:bank_name) %>
    <%= f.text_field :bank_name %>
  </div>
  <div class="field">
    <%= f.label :current_account, t(:current_account) %>
    <%= f.text_field :current_account %>
  </div>
  <div class="field">
    <%= f.label :correspondent_account, t(:correspondent_account) %>
    <%= f.text_field :correspondent_account %>
  </div>
  <div class="field">
    <%= f.label :bik, t(:bik) %>
    <%= f.text_field :bik %>
  </div>
  <div class="field">
    <%= f.label :bank_person, t(:bank_person) %>
    <%= f.text_field :bank_person %>
  </div>
  <div class="field">
    <%= f.label :type_of_certificate, t(:type_of_certificate) %>
    <%= f.select :type_of_certificate, options_for_select([
      "ГОСТ ISO 9001-2011 (ISO 9001:2008)",
      "ГОСТ Р ИСО 14001-2007 (ISO 14001:2004)",
      "ГОСТ Р 12.0.230-2007 (OHSAS 18001:2007)",
      "SA 8000:2008",">ГОСТ Р ИСО/МЭК 27001-2006 (ISO/IEC 27001:2005)",
      "ISO 50001:2011","ISO 22000:2005","ISO 22301:2012",
      "Интегрированная система менеджманта качества серии ISO 9000"]) %>
  </div>
  <div class="field">
    <%= f.label :auditors_name, t(:auditors_name) %>
    <%= f.text_field :auditors_name %>
  </div>
  <div class="field">
    <%= f.label "1. ", "1. ", :align => "right" %>
    <%= tag "input", type: 'textfield', class: 'auditor' %>
  </div>
  <div class="field">
    <%= f.label "2. ", "2. ", :align => "right" %>
    <%= tag "input", type: 'textfield', class: 'auditor' %>
  </div>
  <div class="field">
    <%= f.label "3. ", "3. ", :align => "right" %>
    <%= tag "input", type: 'textfield', class: 'auditor' %>
  </div>
  <div class="field">
    <%= f.label :categories_list_of_works, t(:categories_list_of_works) %><br />
    <%= f.text_area :categories_list_of_works %>
      <% @level_1_categories.each do |level1| %>
        <%= tag "input", type: 'checkbox', name: level1.id, value: level1.full_title %> 
        <%= f.label level1.id, level1.full_title %>
	<br />
	<div class="subcategory" id=<%= level1.id %> >
	  <% @level_2_categories_with_parent_ids[level1.path].each do |level2| %>
	    <%= tag "input", type: 'checkbox', name: level2.id, value: level2.full_title %> 
	    <%= f.label level2.id, level2.full_title %>
	    <br />
	    <div class="subsubcategory" id=<%= level2.id %> >
	      <% @level_3_categories_with_parent_ids[level2.path].each do |level3| %>
		<%= tag "input", type: 'checkbox', name: level3.id, value: level3.full_title %> 
		<%= f.label level3.id, level3.full_title %>
		<br />
	      <% end %>
	    </div>
	  <% end %>
	</div>
      <% end %>
  </div>
  <div class="field">
    <%= f.label :categories_list_of_works, t(:categories_list_of_works) %><br />
    <%= f.text_area :categories_list_of_works %>
    <% 1.upto(10) do |category_id| %>
      <% (Category.all.select { |category| category.path =~ /\A#{category_id}\.\z/ }).each do |category| %>
        <% name_id = category_id %>
        <%= tag "input", type: 'checkbox', name: name_id, value: category[:path] + " " + category[:name] %> 
        <%= f.label name_id, category[:path] + " " + category[:name] %><br/>
        <div class="subcategory" id= <%= name_id %> >
          <% 1.upto(100) do |subcategory_id| %>
            <% (Category.all.select { |category| category.path =~ /\A#{category_id}\.#{subcategory_id}\.\z/ }).each do |category| %>
              <% name_id = category_id + subcategory_id * 10 %>
              <%= tag "input", type: 'checkbox', name: name_id, value: category[:path] + " " + category[:name] %> 
              <%= f.label name_id, category[:path] + " " + category[:name] %><br/>
              <div class="subsubcategory" id= <%= name_id %> >
                 <% 1.upto(20) do |subsubcategory_id| %>
                   <% (Category.all.select { |category| category.path =~ /\A#{category_id}\.#{subcategory_id}\.#{subsubcategory_id}\.\z/ }).each do |category| %>
                      <% name_id = category_id + subcategory_id * 10 + subsubcategory_id * 100 %>
                      <%= tag "input", type: 'checkbox', name: name_id, value: category[:path] + " " + category[:name] %> 
                      <%= f.label name_id, category[:path] + " " + category[:name] %><br/>
                      <div class="subsubsubcategory" id= <%= name_id %> >
                         <% 1.upto(20) do |subsubsubcategory_id| %>
                            <% (Category.all.select { |category| category.path =~ /\A#{category_id}\.#{subcategory_id}\.#{subsubcategory_id}\.#{subsubcategory_id}\.\z/ }).each do |category| %>
                               <% name_id = category_id + subcategory_id * 10 + subsubcategory_id * 100 + subsubsubcategory_id * 1000 %>
                               <%= tag "input", type: 'checkbox', name: name_id, value: category[:path] + " " + category[:name] %> 
                               <%= f.label name_id, category[:path] + " " + category[:name] %><br/>
                            <% end %>
                         <% end %>
                      </div>
                   <% end %>
                <% end %>
	      </div>
	    <% end %>
	  <% end %>
	</div>
      <% end %>
    <% end %>
    <%= tag "input", type: 'checkbox', id: 'otherCheckBox' %> 
    <%= f.label "other", t(:other) %>
    <%= text_area "other", "other", :id => 'otherTextArea' %>
  </div>
  <div class="actions">
    <%= f.submit :value => t(:submit_create_form) %>
  </div>
<% end %>

app/views/forms/edit.html.erb
<h1>Редактирование форм</h1>

<%= render 'form' %>

<%= link_to t(:show_form), @form %> |
<%= link_to t(:back_to_forms), forms_path %>

app/views/forms/index.html.erb
<h1>Форма для сертификата</h1>
<table class='document'>
<% @forms.each do |form| %>
  <tr>
    <th><%= t(:type_of_legal_entity) %></th>
    <td class='type_of_legal_entity'><%= form.type_of_legal_entity %></td>
  </tr>
  <tr>
    <th><%= t(:company) %></th>
    <td><%= form.company %></td>
  </tr>
  <tr>
    <th><%= t(:creator_name) %></th>
    <td><%= form.creator_name %></td>
  </tr>
  <tr>
    <th><%= t(:registered_address) %></th>
    <td><%= form.registered_address %></td>
  </tr>
  <tr>
    <th><%= t(:actual_address) %></th>
    <td><%= form.actual_address %></td>
  </tr>
  <tr>
    <th><%= t(:address_on_english) %></th>
    <td><%= form.address_on_english %></td>
  </tr>
  <tr>
    <th><%= t(:phone) %></th>
    <td><%= form.phone %></td>
  </tr>
  <tr>
    <th><%= t(:fax) %></th>
    <td><%= form.fax %></td>
  </tr>
  <tr>
    <th><%= t(:email) %></th>
    <td><%= form.email %></td>
  </tr>
  <tr>
    <th><%= t(:inn) %></th>
    <td><%= form.inn %></td>
  </tr>
  <tr>
    <th><%= t(:kpp) %></th>
    <td><%= form.kpp %></td>
  </tr>
  <tr>
    <th><%= t(:ogrn) %></th>
    <td><%= form.ogrn %></td>
  </tr>
  <tr>
    <th><%= t(:bank_name) %></th>
    <td><%= form.bank_name %></td>
  </tr>
  <tr>
    <th><%= t(:current_account) %></th>
    <td><%= form.current_account %></td>
  </tr>
  <tr>
    <th><%= t(:correspondent_account) %></th>
    <td><%= form.correspondent_account %></td>
  </tr>
  <tr>
    <th><%= t(:bik) %></th>
    <td><%= form.bik %></td>
  </tr>
  <tr>
    <th><%= t(:bank_person) %></th>
    <td><%= form.bank_person %></td>
  </tr>
  <tr>
    <th><%= t(:type_of_certificate) %></th>
    <td><%= form.type_of_certificate %></td>
  </tr>
  <tr>
    <th><%= t(:auditors_name) %></th>
    <td><%= form.auditors_name %></td>
  </tr>
  <tr>
    <th><%= t(:categories_list_of_works) %></th>
    <td><%= form.categories_list_of_works %></td>
  </tr>
</table>
  
<table class='actions'>
  <tr>
    <td><%= link_to t(:show_form), form %></td>
    <td><%= link_to 'Отредактировать', edit_form_path(form) %></td>
    <td><%= link_to 'Удалить', form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Form', new_form_path %>

app/views/forms/new.html.erb
<h1> <%= t(:new_form) %> </h1>

<%= render 'form' %>

<%= link_to t(:back_to_forms), forms_path %>

app/views/forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b> type of legal entity:</b>
  <%= @form.type_of_legal_entity %>
</p>

<p>
  <b>Company:</b>
  <%= @form.company %>
</p>

<p>
  <b>Creator name:</b>
  <%= @form.creator_name %>
</p>

<p>
  <b>Registered address:</b>
  <%= @form.registered_address %>
</p>

<p>
  <b>Actual address:</b>
  <%= @form.actual_address %>
</p>

<p>
  <b>address on english:</b>
  <%= @form.address_on_english %>
</p>

<p>
  <b>Phone:</b>
  <%= @form.phone %>
</p>

<p>
  <b>Fax:</b>
  <%= @form.fax %>
</p>

<p>
  <b>Email:</b>
  <%= @form.email %>
</p>

<p>
  <b>Inn:</b>
  <%= @form.inn %>
</p>

<p>
  <b>Kpp:</b>
  <%= @form.kpp %>
</p>

<p>
  <b>Ogrn:</b>
  <%= @form.ogrn %>
</p>

<p>
  <b>Bank name:</b>
  <%= @form.bank_name %>
</p>

<p>
  <b>Current account:</b>
  <%= @form.current_account %>
</p>

<p>
  <b>Correspondent account:</b>
  <%= @form.correspondent_account %>
</p>

<p>
  <b>Bik:</b>
  <%= @form.bik %>
</p>

<p>
  <b>Bank person:</b>
  <%= @form.bank_person %>
</p>

<p>
  <b>Type of certificate:</b>
  <%= @form.type_of_certificate %>
</p>

<p>
  <b>Auditors name:</b>
  <%= @form.auditors_name %>
</p>

<p>
  <b>Categories list of works:</b>
  <%= @form.categories_list_of_works %>
</p>


<%= link_to 'Edit', edit_form_path(@form) %> |
<%= link_to 'Back', forms_path %>

app/views/home/index.html.erb
<h1>Добро пожаловать!</h1>
<p>Вы находитесь на сайте для оформления сертификатов.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Сертификаты</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
  <div id="banner">
    <% image_tag("logo.png") %>
    <%= @page_title || "Сертификаты" %>
  </div>
  <div id="columns">
    <div id="side"> 
      <ul>
        <%= content_tag(:li, link_to("Домашняя страница", home_path, :id => ("current_page" if current_page? home_path) ) ) %>
        <%= content_tag(:li, link_to("Формы", forms_path, :id => ("current_page" if current_page? forms_path) ) ) %>
        <%= content_tag(:li, link_to("Категории", categories_path, :id => ("current_page" if current_page? categories_path) ) ) %>
      </ul>
    </div>
    <div id="main"> 
    
      <%= yield %>
    
    </div>
    <div id="footer">
      Copyright by Vladislav Petrov 2013
    </div>
  </div>
</body>
</html>